### ISSUE TITLE
Issue with the reference genome files

### ISSUE THREAD

**Issue by jeanq1** [ToolsVanBox/PTATO#3]
Hi, 
Could you provide a link to the reference genome files or a way to create them ? I am missing several files, 
Thanks !
Jean

**Comment by jeanq1** [comment]
Hi, 
To be more specific I cannot find these:
*.full.len
*.genomesize.txt
*.len
*.len.genome

Could you provide us with an example of the first lines of the following files?
Thanks !

**Comment by mroosmalen** [comment]
Hi

Thanks for checking out PTATO. We are still improving the pipeline. I see that not all files are needed, we will test this soon and remove all unnecessary genome files (from the README). You can ignore the *.genomesize.txt file for now, because this is an inhouse create file, with the information about the genome size. To be sure I have add below a small version of the content of each files. Some of the files are duplicates.

*.full.len
```
1	chr1	248956422
2	chr2	242193529
3	chr3	198295559
...
Un_JTFH01001996v1_decoy	chrUn_JTFH01001996v1_decoy	2009
Un_JTFH01001997v1_decoy	chrUn_JTFH01001997v1_decoy	2003
Un_JTFH01001998v1_decoy	chrUn_JTFH01001998v1_decoy	2001
```

*.len
```
1	chr1	248956422
2	chr2	242193529
3	chr3	198295559
...
22	chr22	50818468
X	chrX	156040895
Y	chrY	57227415
```

*.len.genome
```
1	248956422
2	242193529
3	198295559
...
20	64444167
21	46709983
22	50818468
```

*genomesize.txt
```
Autosomal non N genome size: 2745186691
Autosomal genome size: 2875001522
Autosomal and XY non N genome size: 2923716080
Autosomal and XY genome size: 3088269832
Autosomal and XYMT non N genome size: 2923732648
Autosomal and XYMT genome size: 3088286401
Full (incl decoy)  non N genome size: 5674883684
Full (incl decoy) genome size: 5969252268
```

**Comment by jeanq1** [comment]
Thank you very much !
